# Generated by Django 5.1.4 on 2025-01-08 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonorTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobile_number", models.CharField(max_length=15)),
                (
                    "amount_donated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "api_donortest",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DonorModel",
            fields=[
                (
                    "cft_no",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=20, null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("org_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DonationModel",
            fields=[
                ("donation_id", models.AutoField(primary_key=True, serialize=False)),
                ("donation_type", models.CharField(max_length=50)),
                ("donation_cause", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gdpr_consent", models.BooleanField(default=False)),
                ("cft_fund_consent", models.BooleanField(default=False)),
                ("gift_aid_consent", models.BooleanField(default=False)),
                (
                    "payment_intent_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "donation_frequency",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("receipt_generated", models.BooleanField(default=False)),
                ("donation_status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.donormodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_line", models.CharField(blank=True, max_length=255, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.donormodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_mode", models.CharField(max_length=20)),
                ("currency", models.CharField(max_length=10)),
                ("payment_reference", models.CharField(max_length=100, unique=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.donationmodel",
                    ),
                ),
            ],
        ),
    ]
