# Generated by Django 5.1.4 on 2025-01-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationmodel",
            name="donation_cause",
            field=models.CharField(
                choices=[
                    ("building_institutions", "Building of Institutions"),
                    ("sponsoring_child", "Sponsoring a Child"),
                    ("where_needed", "Where Most Needed"),
                    ("option_not_selected", "Option Not Selected"),
                ],
                default="option_not_selected",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="donationmodel",
            name="donation_frequency",
            field=models.CharField(
                blank=True, default="One-Off", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="donationmodel",
            name="donation_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="donationmodel",
            name="donation_type",
            field=models.CharField(
                choices=[
                    ("zakaath", "Zakaath"),
                    ("sadaqah", "Sadaqah"),
                    ("lillah", "Lillah"),
                    ("other", "Other"),
                    ("option_not_selected", "Option Not Selected"),
                ],
                default="option_not_selected",
                max_length=50,
            ),
        ),
    ]
