# Generated by Django 5.1.4 on 2025-01-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_donationmodel_donation_cause_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationmodel",
            name="donation_cause",
            field=models.CharField(
                choices=[
                    ("building_institutions", "Building of Institutions"),
                    ("sponsoring_child", "Sponsoring a Child"),
                    ("where_needed", "Where Most Needed"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="donationmodel",
            name="donation_type",
            field=models.CharField(
                choices=[
                    ("zakaath", "Zakaath"),
                    ("sadaqah", "Sadaqah"),
                    ("lillah", "Lillah"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="currency",
            field=models.CharField(max_length=10, verbose_name="Payment Currency"),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="donation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="api.donationmodel",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="payment_mode",
            field=models.CharField(
                default="Card", max_length=20, verbose_name="Payment Mode"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="payment_reference",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Payment Reference"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Transaction ID"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
