# Generated by Django 5.1.4 on 2025-03-02 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_donationmodel_donation_cause_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeIntentModel",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("donation_id", models.IntegerField(blank=True, null=True)),
                ("payment_intent_id", models.CharField(max_length=100, unique=True)),
                ("client_secret", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(default="requires_payment_method", max_length=50),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stripe Payment Session",
                "verbose_name_plural": "Stripe Payment Sessions",
                "db_table": "stripe_payment_session",
            },
        ),
    ]
