# Generated by Django 5.1.4 on 2025-04-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_stripeintentmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stripeintentmodel",
            options={
                "verbose_name": "Stripe Payment Session",
                "verbose_name_plural": "Stripe models",
            },
        ),
    ]
