# Generated by Django 5.1.4 on 2025-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_stripeintentmodel_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donation_id", models.IntegerField(blank=True, null=True)),
                ("cft_no", models.CharField(blank=True, max_length=50, null=True)),
                ("receipt_generated", models.BooleanField(default=False)),
                (
                    "donation_status",
                    models.CharField(default="received", max_length=20),
                ),
                ("differences", models.TextField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "donation_frequency",
                    models.CharField(
                        blank=True, default="One-Off", max_length=20, null=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=20, null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("org_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_line", models.CharField(blank=True, max_length=255, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                ("fund", models.CharField(blank=True, max_length=50, null=True)),
                ("cause", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gdpr_consent", models.BooleanField(default=False)),
                ("cft_fund_consent", models.BooleanField(default=False)),
                ("gift_aid_consent", models.BooleanField(default=False)),
                ("paymentMode", models.CharField(blank=True, max_length=20, null=True)),
                ("currency", models.CharField(default="GBP", max_length=10)),
                (
                    "transactionId",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("submitted_payload", models.JSONField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
