# Generated by Django 5.1.4 on 2025-06-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_donationpayload"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePaymentSession",
            fields=[
                ("session_id", models.UUIDField(primary_key=True, serialize=False)),
                ("donation_id", models.IntegerField(blank=True, null=True)),
                ("payment_intent_id", models.CharField(max_length=100, unique=True)),
                ("client_secret", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "stripe_payment_session",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="donationpayload",
            name="email",
        ),
    ]
