# Generated by Django 5.1.4 on 2025-06-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_stripepaymentsession_remove_donationpayload_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpayload",
            name="email",
            field=models.EmailField(default="dummy@email.com", max_length=254),
            preserve_default=False,
        ),
    ]
