# Generated by Django 5.1.4 on 2025-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_donationpayload_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpayload",
            name="donation_status",
            field=models.CharField(default="received", max_length=50),
        ),
    ]
