# Generated by Django 5.1.4 on 2025-06-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_donationpayload_donation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePaymentSessionView",
            fields=[
                ("session_id", models.UUIDField(primary_key=True, serialize=False)),
                ("donation_id", models.IntegerField(blank=True, null=True)),
                ("payment_intent_id", models.CharField(max_length=100, unique=True)),
                ("client_secret", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Stripe Subscription ID",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Is Recurring?"),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "stripe_payment_session_view",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="StripePaymentSession",
        ),
        migrations.AddField(
            model_name="donationmodel",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Stripe Subscription ID",
            ),
        ),
        migrations.AddField(
            model_name="donationmodel",
            name="subscription_status",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Stripe Subscription Status",
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="is_recurring",
            field=models.BooleanField(default=False, verbose_name="Is Recurring?"),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Stripe Subscription ID",
            ),
        ),
    ]
