# Generated by Django 5.1.4 on 2025-06-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_stripepaymentsessionview_delete_stripepaymentsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="billing_reason",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Billing Reason (Stripe)",
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="invoice_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Hosted Invoice URL"
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="stripe_invoice_id",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Stripe Invoice ID"
            ),
        ),
    ]
