# Generated by Django 5.1.4 on 2025-06-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_paymentmodel_billing_reason_paymentmodel_invoice_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="metadata_json",
            field=models.JSONField(
                blank=True,
                help_text="Optional metadata from Stripe for campaign tracking or internal notes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="next_billing_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Stripe current_period_end: Next scheduled billing date",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="subscription_status",
            field=models.CharField(
                blank=True,
                help_text="Latest status of the Stripe subscription",
                max_length=50,
                null=True,
            ),
        ),
    ]
