# Generated by Django 5.1.4 on 2025-06-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_addressmodel_updated_at_paymentmodel_metadata_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
