# Generated by Django 5.1.4 on 2025-07-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_paymentmodel_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donationpayload",
            old_name="transactionId",
            new_name="transaction_id",
        ),
    ]
