# Generated by Django 5.1.4 on 2025-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_rename_transactionid_donationpayload_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="donormodel",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donormodel",
            name="subscription_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
