# Generated by Django 5.1.4 on 2025-07-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_donormodel_stripe_subscription_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stripepaymentsessionview",
            options={"managed": False},
        ),
    ]
