# Generated by Django 5.1.4 on 2025-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_stripepaymentsessionview_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpayload",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donationpayload",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Stripe Subscription ID",
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
