# Generated by Django 5.1.4 on 2025-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_donationpayload_payment_intent_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeSubscriptionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subscription_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=100)),
                ("webhook_received_at", models.DateTimeField(auto_now_add=True)),
                ("livemode", models.BooleanField(default=False)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
                ("raw_event_payload", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
