# Generated by Django 5.1.4 on 2025-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_stripesubscriptionaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="billing_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="collection_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="customer_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="interval",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="invoice_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="invoice_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="plan_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscriptionaudit",
            name="price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="donationmodel",
            name="donation_type",
            field=models.CharField(
                choices=[
                    ("zakaath", "Zakaath"),
                    ("sadaqah", "Sadaqah"),
                    ("lillah", "Lillah"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
