# Generated by Django 5.1.4 on 2025-07-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_stripesubscriptionaudit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
