# Generated by Django 5.1.4 on 2025-08-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_paymentmodel_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationmodel",
            name="stripe_invoice_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="stripe_invoice_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
